config/routes.rb
Rails.application.routes.draw do

  resources :buildings
  resources :spaces
  resources :materials
  resources :reports
  resources :customers
  resources :floorplans
  devise_for :users, :path_prefix => 'portal'
  resources :admin
  resources :ahera, only: [:index, :show]
  root 'welcome#index'
  resources :welcome, only: [:index]
  get 'admin/index'
  get 'admin/:id/approve'=> 'admin#approve_user', as: 'approve_user'
  get '/reports/download/:id' => 'reports#download', as: 'reports_download'
  get '/admin' => 'admin#index', as: 'users'
  post  '/admin/new' => 'admin#create'
  get '/admin/new' => 'admin#new', as: 'new_user'
  get '/admin/:id/edit' => 'admin#edit', as: 'edit_user'
  get '/admin/:id' => 'admin#show', as: 'user'
  patch '/admin/:id' => 'admin#update'
  put '/admin/:id' => 'admin#update'
  delete '/admin/:id' => 'admin#destroy'
  get 'ahera/:building_id/:space_id' => 'ahera#display_filtered'
  get '/:building_id' => 'welcome#buildingpanel', as: 'show_building'

end

app/models/floorplan.rb
class Floorplan < ActiveRecord::Base
  has_attached_file :image
  belongs_to :building
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


end

app/controllers/floorplans_controller.rb
class FloorplansController < ApplicationController
  before_action :set_floorplan, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, only: [:create, :show, :edit, :update, :destroy]

  # GET /floorplans
  # GET /floorplans.json
  def index
    @floorplans = Floorplan.all
  end

  # GET /floorplans/1
  # GET /floorplans/1.json
  def show
  end

  # GET /floorplans/new
  def new
    @floorplan = Floorplan.new
  end

  # GET /floorplans/1/edit
  def edit
  end

  # POST /floorplans
  # POST /floorplans.json
  def create
    @floorplan = Floorplan.new(floorplan_params)

    respond_to do |format|
      if @floorplan.save
        format.html { redirect_to @floorplan, notice: 'Floorplan was successfully created.' }
        format.json { render :show, status: :created, location: @floorplan }
      else
        format.html { render :new }
        format.json { render json: @floorplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /floorplans/1
  # PATCH/PUT /floorplans/1.json
  def update
    respond_to do |format|
      if @floorplan.update(floorplan_params)
        format.html { redirect_to @floorplan, notice: 'Floorplan was successfully updated.' }
        format.json { render :show, status: :ok, location: @floorplan }
      else
        format.html { render :edit }
        format.json { render json: @floorplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /floorplans/1
  # DELETE /floorplans/1.json
  def destroy
    @floorplan.destroy
    respond_to do |format|
      format.html { redirect_to floorplans_url, notice: 'Floorplan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_floorplan
      @floorplan = Floorplan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def floorplan_params
      params.require(:floorplan).permit(:level, :building_id, :image)

   end
end

app/helpers/floorplans_helper.rb
module FloorplansHelper

def embedded_svg(filename, options = {})
    assets = Rails.application.assets
    file = assets.find_asset(filename).body.force_encoding("UTF-8")
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css "svg"
    if options[:class].present?
      svg["class"] = options[:class]
    end
    raw doc
  end
end

app/views/floorplans/_form.html.erb
<%= form_for(@floorplan, multipart: true) do |f| %>
  <% if @floorplan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@floorplan.errors.count, "error") %> prohibited this floorplan from being saved:</h2>

      <ul>
      <% @floorplan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">   
  <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
    <div class="field">
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </div>
 <div class="field">
  <%= f.label "Building" %><br>
      <%= f.collection_select :building_id, Building.order(:buildingname), :id, :buildingname, include_blank: false %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/floorplans/edit.html.erb
<h1>Editing Floorplan</h1>

<%= render 'form' %>

<%= link_to 'Show', @floorplan %> |
<%= link_to 'Back', floorplans_path %>

app/views/floorplans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Floorplans</h1>

<table>
  <thead>
    <tr>
      
      <td>Building</td>
      <td>Level</td>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @floorplans.each do |floorplan| %>
      <tr>
        <td><%= floorplan.building.buildingname%></td>
        <td><%= floorplan.level%></td>
        <td><%= floorplan.image_file_name%></td>
        <td><%= link_to 'Show', floorplan %></td>
        <td><%= link_to 'Edit', edit_floorplan_path(floorplan) %></td>
        <td><%= link_to 'Destroy', floorplan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Floorplan', new_floorplan_path %>

app/views/floorplans/new.html.erb
<h1>New Floorplan</h1>

<%= render 'form' %>

<%= link_to 'Back', floorplans_path %>

app/views/floorplans/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Building:</strong>
  <%= @floorplan.building.buildingname %>
</p>
<p>
  <strong>Level:</strong>
  <%= @floorplan.level %>
</p>
<p>
  <strong>Filename:</strong>
  <%= @floorplan.image_file_name %>
</p>
<p>
  <strong>Image:</strong>
  <%= inline_svg @floorplan.image_file_name, data: {type: "image/svg+xml"}  %>
 
</p>

<%= link_to 'Edit', edit_floorplan_path(@floorplan) %> |
<%= link_to 'Back', floorplans_path %>