config/routes.rb
Rails.application.routes.draw do

  resources :buildings
  resources :spaces
  resources :materials
  resources :reports
  resources :customers
  resources :floorplans
  devise_for :users, :path_prefix => 'portal'
  resources :admin
  resources :ahera, only: [:index, :show]
  root 'welcome#index'
  resources :welcome, only: [:index]
  get 'admin/index'
  get 'admin/:id/approve'=> 'admin#approve_user', as: 'approve_user'
  get '/reports/download/:id' => 'reports#download', as: 'reports_download'
  get '/admin' => 'admin#index', as: 'users'
  post  '/admin/new' => 'admin#create'
  get '/admin/new' => 'admin#new', as: 'new_user'
  get '/admin/:id/edit' => 'admin#edit', as: 'edit_user'
  get '/admin/:id' => 'admin#show', as: 'user'
  patch '/admin/:id' => 'admin#update'
  put '/admin/:id' => 'admin#update'
  delete '/admin/:id' => 'admin#destroy'
  get 'ahera/:building_id/:space_id' => 'ahera#display_filtered'
  get '/:building_id' => 'welcome#buildingpanel', as: 'show_building'

end

app/views/admin/_edit.html.erb
<%= form_for(@user, :url => {:controller =>'admin', :action =>'update'}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <% if @validatable %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.text_field :password, autocomplete: "off", value: $calc_pass %> 
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation, autocomplete: "off", value: $calc_pass %>
  </div>
  <div class="field">
  <%= f.label "Customer" %><br>
      <%= f.collection_select :customer_id, Customer.order(:company), :id, :company, include_blank: false %>
  </div>
  <div class="field">
    <%= f.label :is_admin %><br>
    <%= f.text_field :is_admin %>
  </div>
    <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/admin/_form.html.erb
<%= form_for(@user, :url => {:controller =>'admin', :action =>'update'}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :encrypted_password %><br>
    <%= f.text_field :encrypted_password %>
  </div>
  <div class="field">
  <%= f.label "Customer" %><br>
      <%= f.collection_select :customer_id, Customer.order(:company), :id, :company, include_blank: false %>
  </div>
  <div class="field">
    <%= f.label :is_admin %><br>
    <%= f.text_field :is_admin %>
  </div>
    <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/admin/_form_new.html.erb
<%= form_for(@user, :url => {:controller =>'admin', :action =>'new'}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :encrypted_password %><br>
    <%= f.text_field :encrypted_password %>
  </div>
  <div class="field">
  <%= f.label "Customer" %><br>
      <%= f.collection_select :customer_id, Customer.order(:company), :id, :company, include_blank: false %>
  </div>
  <div class="field">
    <%= f.label :is_admin %><br>
    <%= f.text_field :is_admin %>
  </div>
    <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/admin/_new.html.erb
<%= form_for(@user, :url => {:controller =>'admin', :action =>'create'}) do |f| %>
  <%= @user.errors %>

  <% if @user.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% @user.temp_pass = Devise.friendly_token.first(8) %>
<% @user.save%>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <% if @validatable %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.text_field :password, autocomplete: "off", readonly: 'false', value: @user.temp_pass %> 
  </div>
  <div class="field" id='invis'>
    <%= f.label :temp_pass %>
    <%= f.text_field :temp_pass, autocomplete: "off", readonly: 'false', value: @user.temp_pass %> 
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation, autocomplete: "off", readonly: 'false', value: @user.temp_pass %>
  </div>
  <div class="field">
  <%= f.label "Customer" %><br>
      <%= f.collection_select :customer_id, Customer.order(:company), :id, :company, include_blank: false %>
  </div>
  <div class="field">
    <%= f.label "User is an admin"%><br>
    <%= f.check_box :is_admin %>
  </div>
    <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/admin/edit.html.erb
<h2>Editing users</h2>

<%= render 'edit' %>

<%= link_to 'Show', user_path %> |
<%= link_to 'Back', users_path %>

app/views/admin/index.html.erb
<h1>User List</h1>

<h3><%= link_to "All Users", :action => "index" %>

<%= link_to "Users awaiting approval", :action => "index", :approved => "false" %></h3>
<h3><table>
  <% @users.each do |user| %>
    <tr>
    <td>
        <%= user.id %>
      </td>
      <td>
        <%= user.email %>
      </td>
      <td>
        <%= user.customer_id %>
      </td>
      <td>
        <%= translate(user.approved.class) %>
      </td>
      <td>
      <% if !user.approved %>
     <%= link_to "Approve", approve_user_path(user.id)  %>
     <% else%>
     <%= link_to "De-approve", approve_user_path(user.id)  %>
     <% end %>
      </td>
         
        
       <td><%= link_to 'Show', user_path(user) %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td>
    </tr>
  <% end %>
</table>
<%= link_to 'New User', new_user_path %>
</h3>

app/views/admin/new.html.erb
<h1>New user</h1>

<%= render 'new' %>

<%= link_to 'Back', admin_index_path %>

app/views/admin/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @user.id %>
</p>


<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Encrypted Pass:</strong>
  <%= @user.encrypted_password %>
</p>

<p>
  <strong>User is Admin:</strong>
  <%= @user.is_admin %>
</p>

<p>
  <strong>customer:</strong>
  <% if @user.customer != nil %>
  <%= @user.customer.company.to_s %>
  <% else %>
  No cusomter assigned. 
  <% end %>
</p>


<%= link_to 'Edit', edit_admin_path(@user) %> |
<%= link_to 'Back', admin_index_path %>