config/routes.rb
Rails.application.routes.draw do

  resources :buildings
  resources :spaces
  resources :materials
  resources :reports
  resources :customers
  resources :floorplans
  devise_for :users, :path_prefix => 'portal'
  resources :admin
  resources :ahera, only: [:index, :show]
  root 'welcome#index'
  resources :welcome, only: [:index]
  get 'admin/index'
  get 'admin/:id/approve'=> 'admin#approve_user', as: 'approve_user'
  get '/reports/download/:id' => 'reports#download', as: 'reports_download'
  get '/admin' => 'admin#index', as: 'users'
  post  '/admin/new' => 'admin#create'
  get '/admin/new' => 'admin#new', as: 'new_user'
  get '/admin/:id/edit' => 'admin#edit', as: 'edit_user'
  get '/admin/:id' => 'admin#show', as: 'user'
  patch '/admin/:id' => 'admin#update'
  put '/admin/:id' => 'admin#update'
  delete '/admin/:id' => 'admin#destroy'
  get 'ahera/:building_id/:space_id' => 'ahera#display_filtered'
  get '/:building_id' => 'welcome#buildingpanel', as: 'show_building'

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :customer
  belongs_to :building
  mount_uploader :pdf, ReportsUploader 
  
  validates_presence_of :reportname, :description, :filename, :customer_id, :report_date, :building_id

end

app/controllers/reports_controller.rb
class ReportsController < InternalController
  before_action  :set_report, only: [:show, :edit, :update, :destroy, :download, :check_ownership]
before_filter :check_ownership, only: [:show, :edit, :update, :destroy, :download]
before_filter :check_admin, only: [:create, :edit, :update, :destroy]
  respond_to :html



def index
    @user = current_user
    @customer = current_user.customer
    if !current_user.is_admin

     cust_reports = current_user.customer.reports
       
     @reports_grid = initialize_grid(cust_reports,
      :include => [:customer, :building],
      #:conditions => {:customer => @customer},
      :per_page => 10
      )
    else
    @reports_grid = initialize_grid(Report,
      :include => [:customer, :building],
      #:conditions => {:customer => false},
      :per_page => 10
      )
    end
end
     
       

def show
    respond_with(@report)
end

def new
    @report = Report.new
    respond_with(@report)
end

def edit
  @building =  @report.building
 @customer = @report.customer
  

end

def create
    @report = Report.new(report_params)
    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
end

def update
   
    

    @report.update(report_params)
    @report = Report.find(params[:id])
    @report.customer_id = @report.building.customer_id
    @report.update(report_params)
    respond_with(@report)
end

def destroy
    @report.destroy
    respond_with(@report)
end
  
def download
  if ENV['MY_ENV'] != 'production'
    data = open(@report.pdf.to_s) 
    send_data data.read, filename: @report.filename, type: "application/pdf", disposition: 'inline', stream: 'true', buffer_size: '4096' 
  else
    send_file File.join("public", "pdf_reports", @report.customer_id.to_s, @report.filename), :type=> "application/pdf", :x_sendfile=>true
  end
end

def check_ownership
      if current_user.customer_id != @report.customer_id && !current_user.is_admin #check if current user is a user tied to report's owner
         redirect_to reports_path,
          alert: "You are not authorized to load this report." # boot them to the main page if not admin
      end
end
     

private

    def set_report
      @report = Report.find(params[:id])
    end
    
 

    def report_params
      params.require(:report).permit(:reportname, :description, :filename, :customer_id, :report_date, :pdf, :building_id)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for @report, :html => {:multipart => true} do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Report Title"%><br>
    <%= f.text_field :reportname %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">   
  <%= f.label "Select a file to upload. Matching filenames will be overwritten."%><br>
    <%= f.file_field :pdf %>
  </div>
  <% if current_user.is_admin %>
      
        <div class="field">
          <%= f.label "Customer" %><br>
          <%= f.collection_select :customer_id, Customer.order(:company), :id, :company, include_blank: false  %>
        </div>
  
  <div class="field">
    <%= f.label "Building" %><br>
      <%= f.collection_select :building_id, Building.order(:buildingname), :id, :buildingname, include_blank: false %>
  </div>

    <% else %>
    <%= f.label "Customer" %>
    <%= f.text_area :customer, :readonly => true, :value => current_user.customer  %>
  <% end %>

  <div class="field">
    <%= f.label :report_date %><br>
    <%= f.date_field  :report_date, :class => "hasDatepicker",:id =>'datepicker' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/_grid.html.erb
<%= grid(@reports_grid, show_filters: :always) do |g|


g.column name:  'Report', attribute: 'reportname', auto_reload: false
g.column name:  'Description', attribute: 'description', auto_reload: false
g.column name:  'Date', attribute: 'report_date', model: 'Report', auto_reload: false, helper_style: :html5  do |report|
report.report_date.to_formatted_s(:long)
end

if current_user.is_admin
    g.column name: 'Customer', attribute: 'company', model: 'Customer', auto_reload: false  do |report|
    report.customer.company if  report.customer
  end 
   g.column do |report|
    link_to('Show', report)
   end
   g.column do |report|
    link_to('Edit', edit_report_path(report))
   end
   g.column do |report|
    link_to('Destroy', report, method: :delete, data: { confirm: 'Are you sure?' })
   end

end
    g.column do |report|
   link_to('Download', reports_download_path(report.id))  
   end

   # g.column name:  'Report', attribute: 'pdf', auto_reload: false  #uncomment to display download link for debug
  g.blank_slate  do
    content_tag :div, "No records found", class: 'well'
  end

end -%>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<h3>
<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>
</h3>

app/views/reports/index.html.erb
<div class="reportheader"><h4>
<% unless current_user.is_admin %>
<%= 'Viewing reports for ' + @customer.company %> 
<% else%>
<%= 'Viewing reports for all customers'%> 
<% end %> | 
<%= link_to 'View AHERA data', ahera_index_path %>
</h4>
</div>
<%= render partial:  'grid' %>


<br>
<% if current_user.is_admin %>
<h3><%= link_to 'New Report', new_report_path %></h3>
<% end%>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<h3><%= link_to 'Back', reports_path %></h3>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reportname:</strong>
  <%= @report.reportname %>
</p>

<p>
  <strong>Description:</strong>
  <%= @report.description %>
</p>

<p>
  <strong>Filename:</strong>
  <%= @report.filename %>
</p>
<p>
  <strong>Building:</strong>
  <%= @report.building.buildingname %>
</p>
<p>
  <strong>Customer:</strong>
  <%= @report.customer.company %>
</p>

<p>
  <strong>Report date:</strong>
  <%= @report.report_date %>
</p>
<p>
  <strong>Download URL:</strong>
  <%= @report.pdf %>
</p>
<h3>
<% if current_user.is_admin %>
<%= link_to 'Edit', edit_report_path(@report) %> |
<% end %>
<%= link_to 'Back', reports_path %>
</h3>