config/routes.rb
Rails.application.routes.draw do

  resources :buildings
  resources :spaces
  resources :materials
  resources :reports
  resources :customers
  resources :floorplans
  devise_for :users, :path_prefix => 'portal'
  resources :admin
  resources :ahera, only: [:index, :show]
  root 'welcome#index'
  resources :welcome, only: [:index]
  get 'admin/index'
  get 'admin/:id/approve'=> 'admin#approve_user', as: 'approve_user'
  get '/reports/download/:id' => 'reports#download', as: 'reports_download'
  get '/admin' => 'admin#index', as: 'users'
  post  '/admin/new' => 'admin#create'
  get '/admin/new' => 'admin#new', as: 'new_user'
  get '/admin/:id/edit' => 'admin#edit', as: 'edit_user'
  get '/admin/:id' => 'admin#show', as: 'user'
  patch '/admin/:id' => 'admin#update'
  put '/admin/:id' => 'admin#update'
  delete '/admin/:id' => 'admin#destroy'
  get 'ahera/:building_id/:space_id' => 'ahera#display_filtered'
  get '/:building_id' => 'welcome#buildingpanel', as: 'show_building'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demonstration Customer Data Portal</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

 <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
 



</head>



<body>
  <div class='center'>


        <div class='navbar'>

                <p class="navbar-text pull-right">
              <% if user_signed_in? %>
                Logged in as <strong><%= current_user.email %></strong>. |
                
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                <% if false %>
                <% end %>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
              <% if false %>
                <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
                <% end %>
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
              <% end %>

        </div>
        
        

          <div class='logo'>
            <%= link_to(image_tag('logo.png', :alt => 'logo'), root_path) %>
          </div>

       

          <div class='navfade'>
            <%= image_tag('navfade.png', :alt => 'navfade') %>
          

        

        <h1>
          Demonstration Customer Data Portal
        </h1>
</div>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

 <% debug @user %>
 
 <% if current_user %> 
<div id="top-menu-container">
 <% if current_user.is_admin %>
  <ul  id="menu">
    <li><%= link_to 'Home', welcome_index_path %></li>
    <li><%= link_to 'Asbestos', ahera_index_path %></li>
    <li><%= link_to 'Reports', reports_path %></li>
    <li><%= link_to 'Admin', admin_index_path %></li>


  </ul>
  <% else  %>
  <ul  id="menu">
    <li><%= link_to 'Home', welcome_index_path %></li>
    <li><%= link_to 'Asbestos', ahera_index_path %></li>
    <li><%= link_to 'Reports', reports_path %></li>
  </ul>
  <% end %>
  </div>
<% end %>

<script>
$( "#menu" ).menu();
</script>
      <%= yield %>



  </div>

 
</body>

</html>